classes:
- service.fluentbit.config

parameters:
  fluentbit:
    config:
      input:
        system.conf:
          kmsg:
            tag: system.log.kernel
          syslog:
            chunk_size: 32
            buffer_size: 64
            path: ${_param:fluentbit_config_syslogpath}/syslog
            tag: system.log.syslog
          systemd:
            tag: host.*
            systemd_filter:
              - _SYSTEM_UNIT=*.service
              - _SYSTEM_UNIT=*.network
              - _SYSTEM_UNIT=*.boot
      service:
        td-agent-bit.conf:
          - '@INCLUDE input_system.conf'

